### ISSUE TITLE
Thanks & Config File

### ISSUE THREAD

**Issue by Logic-gate** [cybre/budgie-haste-applet#7]
Hey, just dropping in to say thanks for this. I added it to the clients list here(https://github.com/seejohnrun/haste-server/wiki/Clients).

Is there by any chance a config file file for specifying the server? or is [L25](https://github.com/cybre/budgie-haste-applet/blob/0830035bcbe54478a9b219ad37204e0d8659e6ed/budgie-haste-applet/NewHasteView.vala#L25) the only way to define a new server?

**Comment by cybre** [comment]
You can change the server in raven (the budgie-desktop sidebar). Select the applet in the applet list and click the cog button. It uses gsettings to store the data.

**Comment by Logic-gate** [comment]
Hey, 

Thanks for the config inst. However, for some reason I am getting a `Error. Connection to server failed`. mind you I added `https://`. I am not sure what I did, but reverting back to `hastebin.com` raises the same error. Is there a cache of some sorts that needs to be cleared??

**Comment by cybre** [comment]
Hmm. I'll investigate when I get home from school.

**Comment by cybre** [comment]
Fixed! I'll wait for you to try it out to close the issue. I used your server for testing so sorry for the spam xD.

**Comment by Logic-gate** [comment]
Hey,

Thanks for going through with this. 

Unfortunately it's not working for me. I keep getting this error.

```
(budgie-panel:1497): GLib-GIO-ERROR **: Settings schema 'com.github.cybre.haste-applet' does not contain a key named 'protocol'
Trace/breakpoint trap (core dumped)
```

So, I added 

```
<key type="s" name="protocol">
      <default>'https'</default>
      <summary>protocol</summary>
      <description>protocol</description>
</key>
```

But, I still get the same error. Keep in mind, budgie panel in its entirety fails to load due to the error.

Could you please try it on `https://ma.tc`

I am sure it's a misunderstanding from my part.

cheers, and thanks.

**Comment by cybre** [comment]
Ah, completely my fault. I have somehow managed to not include that key in the commit. It's now there. Rebuild please.

EDIT: That URL works.

**Comment by Logic-gate** [comment]
Interesting...how did you get it to work??

This is the out put I get

```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://ma.tc/documents">here</a>.</p>
</body></html>

Status Code: 301
```

EDIT: I am still getting a connection error.
I followed the build instructions stated. I only changed the the address and protocol in `NewHasteView` and `gschema`

**Comment by cybre** [comment]
Did you include the protocol?

**Comment by Logic-gate** [comment]
Yup

**Comment by cybre** [comment]
This is so weird.

**Comment by cybre** [comment]
Don't change it in the files. Leave it as it is and change in the settings.

**Comment by Logic-gate** [comment]
aha...wait, let me try it your way.

**Comment by Logic-gate** [comment]
Should I change it pre or post build?

**Comment by Logic-gate** [comment]
Ohhhhhhh.....My bad. Just disregard everything I said.

**Comment by cybre** [comment]
What was it?

**Comment by Logic-gate** [comment]
i kept changing the address and protocol in gschema manually...didn't realize that there was a settings option in raven. This is so embarrassing. Sorry for being the idiot of the day. Drat and double drat.

**Comment by Logic-gate** [comment]
Thanks for everything...I probably wasted your valuable time. It's working flawlessly now.

**Comment by cybre** [comment]
Haha, I even explained it in my first response :P. Well, at least I've finally added https support. Cheers!
